.

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -7,9 +7,63 @@ jobs:
     name: ruff
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - name: Lint with ruff 
-        uses: chartboost/ruff-action@v1
+      - uses: actions/checkout@v4
+      - name: Set up Python
+        uses: actions/setup-python@v5
         with:
-          src: "."
-          version: 0.0.290
+          python-version-file: pyproject.toml
+      - name: Install ruff and requirements
+        run: |
+          pip3 install -r <(cat requirements_dev.txt | grep '^ruff==')
+      - name: Run ruff
+        run: |
+          set +e  # Do not exit shell on ruff failure
+
+          nonzero_exit=0
+          files=$(find . -type f -name "*.py" | sort)
+          while read file; do
+            out=$(ruff check --force-exclude "$file" 2> ruff_stderr.txt)
+            exit_code=$?
+            err=$(<ruff_stderr.txt)
+
+            if [[ $exit_code -ne 0 ]]; then
+              nonzero_exit=$exit_code
+            fi
+
+            if [[ -n "$out" ]]; then
+              # Display the raw output in the step
+              echo "${out}"
+              # Display the Markdown output in the job summary
+              echo "\`\`\`python" >> $GITHUB_STEP_SUMMARY
+              echo "${out}" >> $GITHUB_STEP_SUMMARY
+              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+            fi
+            if [[ -n "$err" ]]; then
+              echo "${err}"
+              echo "\`\`\`python" >> $GITHUB_STEP_SUMMARY
+              echo "${err}" >> $GITHUB_STEP_SUMMARY
+              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+            fi
+
+            out=$(ruff check --diff --force-exclude "$file" 2> ruff_stderr.txt)
+            err=$(<ruff_stderr.txt)
+
+            if [[ -n "$out" ]]; then
+              # Display the raw output in the step
+              echo "${out}"
+              # Display the Markdown output in the job summary
+              echo "\`\`\`diff" >> $GITHUB_STEP_SUMMARY
+              echo "${out}" >> $GITHUB_STEP_SUMMARY
+              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+            fi
+            if [[ -n "$err" ]]; then
+              echo "${err}"
+              echo "\`\`\`python" >> $GITHUB_STEP_SUMMARY
+              echo "${err}" >> $GITHUB_STEP_SUMMARY
+              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+            fi
+          done <<< "$files"
+
+          # Exit with the first non-zero exit-code returned by ruff
+          # or just zero if all passed
+          exit ${nonzero_exit}
diff --git a/.github/workflows/styles.yml b/.github/workflows/styles.yml
--- a/.github/workflows/styles.yml
+++ b/.github/workflows/styles.yml
@@ -15,14 +15,66 @@ jobs:
           version: latest
           args: --check .
 
-  black:
-    name: Black
+  ruff-format:
+    name: ruff-format
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - name: Check black
-        uses: psf/black@stable
+      - uses: actions/checkout@v4
+      - name: Set up Python
+        uses: actions/setup-python@v5
         with:
-          options: '--check --verbose'
-          src: '.'
-          version: '~= 22.12.0'
+          python-version-file: pyproject.toml
+      - name: Install ruff
+        run: |
+          pip3 install -r <(cat requirements_dev.txt | grep '^ruff==')
+      - name: Run ruff format
+        run: |
+          set +e  # Do not exit shell on black failure
+          out=$(ruff format --check --diff . 2> app_stderr.txt)
+          exit_code=$?
+          err=$(<app_stderr.txt)
+
+          # Display the raw output in the step
+          echo "${out}"
+          echo "${err}"
+
+          # Display the Markdown output in the job summary
+          echo "\`\`\`diff" >> $GITHUB_STEP_SUMMARY
+          echo "${out}" >> $GITHUB_STEP_SUMMARY
+          echo "${err}" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+
+          # Exit with the exit-code returned by ruff
+          exit ${exit_code}
+
+  ruff-isort:
+    name: ruff-isort
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version-file: pyproject.toml
+      - name: Install ruff
+        run: |
+          pip3 install -r <(cat requirements_dev.txt | grep '^ruff==')
+      - name: Run ruff isort
+        run: |
+          set +e  # Do not exit shell on app failure
+          out=$(ruff --select I --diff . 2> app_stderr.txt)
+          exit_code=$?
+          err=$(<app_stderr.txt)
+
+          # Display the raw output in the step
+          echo "${out}"
+          echo "${err}"
+
+          # Display the Markdown output in the job summary
+          echo "\`\`\`diff" >> $GITHUB_STEP_SUMMARY
+          echo "${out}" >> $GITHUB_STEP_SUMMARY
+          echo "${err}" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+
+          # Exit with the exit-code returned by ruff
+          exit ${exit_code}
